name: Update Recent Activity

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    steps:
      - uses: Readme-Workflows/recent-activity@main
        with:
          GH_USERNAME: sairiteshdomakuntla
